//! Package discovery and generated Cargo profile management for MagicBevy.

use serde::Deserialize;
use std::collections::BTreeSet;
use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

const GENERATED_MARKER: &str = "# This file is generated by magic_pkg. Do not edit.\n";

#[derive(Debug)]
pub enum PackageError {
    Io {
        path: PathBuf,
        source: io::Error,
    },
    Manifest {
        path: PathBuf,
        source: serde_json::Error,
    },
    InvalidManifest {
        path: PathBuf,
        message: String,
    },
    DuplicateId(String),
    AlreadyExists(PathBuf),
    InvalidArgument(String),
}

impl fmt::Display for PackageError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => write!(f, "I/O error at {}: {source}", path.display()),
            Self::Manifest { path, source } => write!(
                f,
                "Invalid package manifest at {}: {source}",
                path.display()
            ),
            Self::InvalidManifest { path, message } => write!(
                f,
                "Invalid package manifest at {}: {message}",
                path.display()
            ),
            Self::DuplicateId(id) => write!(f, "Duplicate package identifier: {id}"),
            Self::AlreadyExists(path) => write!(f, "Package already exists at {}", path.display()),
            Self::InvalidArgument(message) => write!(f, "Invalid argument: {message}"),
        }
    }
}

impl std::error::Error for PackageError {}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum PackageTarget {
    Editor,
    Runtime,
}

impl PackageTarget {
    fn directory(self) -> &'static str {
        match self {
            Self::Editor => "editor",
            Self::Runtime => "runtime",
        }
    }

    fn manifest_value(self) -> &'static str {
        match self {
            Self::Editor => "editor",
            Self::Runtime => "runtime",
        }
    }
}

#[derive(Debug, Deserialize)]
struct RawManifest {
    name: String,
    version: String,
    #[serde(default)]
    enabled: Option<bool>,
    #[serde(default)]
    status: Option<String>,
    #[serde(default)]
    targets: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PackageManifest {
    pub vendor: String,
    pub name: String,
    pub version: String,
    pub enabled: bool,
    pub targets: BTreeSet<PackageTarget>,
    pub root: PathBuf,
}

impl PackageManifest {
    pub fn id(&self) -> String {
        format!("{}/{}", self.vendor, self.name)
    }

    fn profile_name(&self) -> String {
        format!(
            "{}_{}",
            cargo_identifier(&self.vendor),
            cargo_identifier(&self.name)
        )
    }
}

#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct SyncReport {
    pub discovered: usize,
    pub enabled: usize,
    pub written_profiles: usize,
    pub removed_profiles: usize,
}

pub struct PackageManager {
    packages_root: PathBuf,
    profiles_root: PathBuf,
}

impl PackageManager {
    pub fn new(workspace_root: impl Into<PathBuf>) -> Self {
        let workspace_root = workspace_root.into();
        Self {
            packages_root: workspace_root.join("packages"),
            profiles_root: workspace_root.join("profiles"),
        }
    }

    pub fn discover(&self) -> Result<Vec<PackageManifest>, PackageError> {
        if !self.packages_root.exists() {
            return Ok(Vec::new());
        }

        let mut packages = Vec::new();
        let mut identifiers = BTreeSet::new();
        for vendor_entry in read_directories(&self.packages_root)? {
            let vendor = file_name(&vendor_entry)?;
            for package_root in read_directories(&vendor_entry)? {
                let package = self.read_manifest(&vendor, package_root)?;
                if !identifiers.insert(package.profile_name()) {
                    return Err(PackageError::DuplicateId(package.id()));
                }
                packages.push(package);
            }
        }
        packages.sort_by(|left, right| left.id().cmp(&right.id()));
        Ok(packages)
    }

    pub fn sync_profiles(&self) -> Result<SyncReport, PackageError> {
        let packages = self.discover()?;
        let mut report = SyncReport {
            discovered: packages.len(),
            ..SyncReport::default()
        };
        let mut expected = BTreeSet::new();

        for package in packages.into_iter().filter(|package| package.enabled) {
            report.enabled += 1;
            for target in &package.targets {
                let profile_dir = self
                    .profiles_root
                    .join(target.directory())
                    .join(package.profile_name());
                expected.insert(profile_dir.clone());
                if self.write_profile(&profile_dir, &package, *target)? {
                    report.written_profiles += 1;
                }
            }
        }

        for target in [PackageTarget::Editor, PackageTarget::Runtime] {
            let target_root = self.profiles_root.join(target.directory());
            if !target_root.exists() {
                continue;
            }
            for profile_dir in read_directories(&target_root)? {
                if !expected.contains(&profile_dir) && is_generated_profile(&profile_dir) {
                    fs::remove_dir_all(&profile_dir).map_err(|source| PackageError::Io {
                        path: profile_dir.clone(),
                        source,
                    })?;
                    report.removed_profiles += 1;
                }
            }
        }
        Ok(report)
    }

    pub fn init_package(
        &self,
        vendor: &str,
        name: &str,
        targets: impl IntoIterator<Item = PackageTarget>,
    ) -> Result<PackageManifest, PackageError> {
        validate_segment("vendor", vendor)?;
        validate_segment("package name", name)?;
        let targets = targets.into_iter().collect::<BTreeSet<_>>();
        if targets.is_empty() {
            return Err(PackageError::InvalidArgument(
                "at least one target is required".into(),
            ));
        }

        let root = self.packages_root.join(vendor).join(name);
        if root.exists() {
            return Err(PackageError::AlreadyExists(root));
        }

        fs::create_dir_all(root.join("assets")).map_err(|source| PackageError::Io {
            path: root.clone(),
            source,
        })?;
        fs::write(root.join("assets/.gitkeep"), "").map_err(|source| PackageError::Io {
            path: root.join("assets/.gitkeep"),
            source,
        })?;

        let target_values = targets
            .iter()
            .map(|target| format!("\"{}\"", target.manifest_value()))
            .collect::<Vec<_>>()
            .join(", ");
        let manifest = format!(
            "{{\n  \"name\": \"{name}\",\n  \"version\": \"0.1.0\",\n  \"status\": \"enabled\",\n  \"targets\": [{target_values}]\n}}\n"
        );
        fs::write(root.join("package.json"), manifest).map_err(|source| PackageError::Io {
            path: root.join("package.json"),
            source,
        })?;

        for target in &targets {
            self.write_target_template(&root, vendor, name, *target)?;
        }
        self.read_manifest(vendor, root)
    }

    pub fn remove_package(&self, vendor: &str, name: &str) -> Result<String, PackageError> {
        validate_segment("vendor", vendor)?;
        validate_segment("package name", name)?;

        let root = self.packages_root.join(vendor).join(name);
        if !root.exists() {
            return Err(PackageError::InvalidArgument(format!(
                "Package '{vendor}/{name}' does not exist at {}",
                root.display()
            )));
        }

        fs::remove_dir_all(&root).map_err(|source| PackageError::Io {
            path: root.clone(),
            source,
        })?;

        self.sync_profiles()?;

        Ok(format!("{vendor}/{name}"))
    }

    pub fn set_package_status(
        &self,
        vendor: &str,
        name: &str,
        enabled: bool,
    ) -> Result<String, PackageError> {
        validate_segment("vendor", vendor)?;
        validate_segment("package name", name)?;

        let root = self.packages_root.join(vendor).join(name);
        let manifest_path = root.join("package.json");

        if !manifest_path.is_file() {
            return Err(PackageError::InvalidArgument(format!(
                "Package '{vendor}/{name}' does not exist at {}",
                root.display()
            )));
        }

        let content = fs::read_to_string(&manifest_path).map_err(|source| PackageError::Io {
            path: manifest_path.clone(),
            source,
        })?;

        let mut json_val: serde_json::Value =
            serde_json::from_str(&content).map_err(|source| PackageError::Manifest {
                path: manifest_path.clone(),
                source,
            })?;

        if let Some(obj) = json_val.as_object_mut() {
            let status_str = if enabled { "enabled" } else { "disabled" };
            obj.insert(
                "status".to_string(),
                serde_json::Value::String(status_str.to_string()),
            );
            obj.remove("enabled");
        }

        let updated_json = serde_json::to_string_pretty(&json_val).map_err(|source| {
            PackageError::InvalidManifest {
                path: manifest_path.clone(),
                message: format!("Failed to serialize JSON: {source}"),
            }
        })?;

        fs::write(&manifest_path, updated_json).map_err(|source| PackageError::Io {
            path: manifest_path,
            source,
        })?;

        self.sync_profiles()?;

        Ok(format!("{vendor}/{name}"))
    }

    fn write_target_template(
        &self,
        package_root: &Path,
        vendor: &str,
        name: &str,
        target: PackageTarget,
    ) -> Result<(), PackageError> {
        let target_root = package_root.join(target.directory());
        let source_root = target_root.join("src");
        fs::create_dir_all(&source_root).map_err(|source| PackageError::Io {
            path: source_root.clone(),
            source,
        })?;
        let crate_name = format!(
            "magic_package_{}_{}_{}",
            cargo_identifier(vendor),
            cargo_identifier(name),
            target.manifest_value()
        );
        let cargo_toml = format!(
            "[package]\nname = \"{crate_name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n"
        );
        fs::write(target_root.join("Cargo.toml"), cargo_toml).map_err(|source| {
            PackageError::Io {
                path: target_root.join("Cargo.toml"),
                source,
            }
        })?;
        let source = match target {
            PackageTarget::Editor => "pub fn register<T>(_manager: &mut T) {}\n",
            PackageTarget::Runtime => "pub fn register_runtime() {}\n",
        };
        fs::write(source_root.join("lib.rs"), source).map_err(|source| PackageError::Io {
            path: source_root.join("lib.rs"),
            source,
        })
    }

    fn read_manifest(&self, vendor: &str, root: PathBuf) -> Result<PackageManifest, PackageError> {
        let path = root.join("package.json");
        if !path.is_file() {
            return Err(PackageError::InvalidManifest {
                path,
                message: "package.json is required".into(),
            });
        }
        let content = fs::read_to_string(&path).map_err(|source| PackageError::Io {
            path: path.clone(),
            source,
        })?;
        let raw: RawManifest =
            serde_json::from_str(&content).map_err(|source| PackageError::Manifest {
                path: path.clone(),
                source,
            })?;
        if raw.name.trim().is_empty() || raw.version.trim().is_empty() {
            return Err(PackageError::InvalidManifest {
                path,
                message: "name and version must not be empty".into(),
            });
        }
        let enabled = match raw.status.as_deref() {
            None => raw.enabled.unwrap_or(true),
            Some("enabled") if raw.enabled != Some(false) => true,
            Some("disabled") if raw.enabled != Some(true) => false,
            Some("enabled") | Some("disabled") => {
                return Err(PackageError::InvalidManifest {
                    path,
                    message: "status and enabled disagree".into(),
                });
            }
            Some(status) => {
                return Err(PackageError::InvalidManifest {
                    path,
                    message: format!("unsupported status '{status}'"),
                });
            }
        };
        let mut targets = BTreeSet::new();
        for target in raw.targets {
            match target.as_str() {
                "editor" => {
                    targets.insert(PackageTarget::Editor);
                }
                "runtime" => {
                    targets.insert(PackageTarget::Runtime);
                }
                _ => {
                    return Err(PackageError::InvalidManifest {
                        path,
                        message: format!("unsupported target '{target}'"),
                    });
                }
            }
        }
        if enabled && targets.is_empty() {
            return Err(PackageError::InvalidManifest {
                path,
                message: "enabled packages require at least one target".into(),
            });
        }
        for target in &targets {
            let crate_manifest = root.join(target.directory()).join("Cargo.toml");
            if !crate_manifest.is_file() {
                return Err(PackageError::InvalidManifest {
                    path: crate_manifest,
                    message: format!("{} target requires a Cargo crate", target.directory()),
                });
            }
        }
        Ok(PackageManifest {
            vendor: vendor.to_owned(),
            name: raw.name,
            version: raw.version,
            enabled,
            targets,
            root,
        })
    }

    fn write_profile(
        &self,
        profile_dir: &Path,
        package: &PackageManifest,
        target: PackageTarget,
    ) -> Result<bool, PackageError> {
        let crate_path = package.root.join(target.directory());
        let crate_name = package_name(&crate_path.join("Cargo.toml"))?;
        let relative_path = relative_path(profile_dir, &crate_path);
        let profile_name = format!(
            "magic_profile_{}_{}",
            target.directory(),
            package.profile_name()
        );
        let dependency_name = format!("package_{}", package.profile_name());
        let manifest = format!(
            "{GENERATED_MARKER}\n\n[package]\nname = \"{profile_name}\"\nversion = \"{}\"\nedition = \"2024\"\npublish = false\n\n[dependencies]\n{dependency_name} = {{ package = \"{crate_name}\", path = \"{}\" }}\n",
            package.version,
            toml_path(&relative_path),
        );
        let manifest_path = profile_dir.join("Cargo.toml");
        let source_path = profile_dir.join("src/lib.rs");
        let changed = fs::read_to_string(&manifest_path)
            .map(|old| old != manifest)
            .unwrap_or(true)
            || !source_path.is_file();
        if changed {
            fs::create_dir_all(profile_dir).map_err(|source| PackageError::Io {
                path: profile_dir.to_path_buf(),
                source,
            })?;
            fs::write(&manifest_path, manifest).map_err(|source| PackageError::Io {
                path: manifest_path,
                source,
            })?;
            let source_dir = profile_dir.join("src");
            fs::create_dir_all(&source_dir).map_err(|source| PackageError::Io {
                path: source_dir.clone(),
                source,
            })?;
            fs::write(&source_path, "// Generated profile crate.\n").map_err(|source| {
                PackageError::Io {
                    path: source_path,
                    source,
                }
            })?;
        }
        Ok(changed)
    }
}

fn validate_segment(kind: &str, value: &str) -> Result<(), PackageError> {
    if value.is_empty()
        || !value.chars().all(|character| {
            character.is_ascii_alphanumeric() || character == '_' || character == '-'
        })
    {
        return Err(PackageError::InvalidArgument(format!(
            "{kind} must use only ASCII letters, digits, '_' or '-'"
        )));
    }
    Ok(())
}

fn package_name(manifest_path: &Path) -> Result<String, PackageError> {
    let contents = fs::read_to_string(manifest_path).map_err(|source| PackageError::Io {
        path: manifest_path.to_path_buf(),
        source,
    })?;
    let mut in_package_table = false;
    for raw_line in contents.lines() {
        let line = raw_line.trim();
        if line.starts_with('[') {
            in_package_table = line == "[package]";
            continue;
        }
        if !in_package_table {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        if key.trim() != "name" {
            continue;
        }
        let value = value.trim();
        let name = match value.chars().next() {
            Some('"') => value[1..].split('"').next(),
            Some('\'') => value[1..].split('\'').next(),
            _ => None,
        };
        if let Some(name) = name.filter(|name| !name.trim().is_empty()) {
            return Ok(name.to_owned());
        }
    }
    Err(PackageError::InvalidManifest {
        path: manifest_path.to_path_buf(),
        message: "Cargo.toml requires a non-empty package.name".into(),
    })
}

fn read_directories(path: &Path) -> Result<Vec<PathBuf>, PackageError> {
    let entries = fs::read_dir(path).map_err(|source| PackageError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    Ok(entries
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .collect())
}

fn file_name(path: &Path) -> Result<String, PackageError> {
    path.file_name()
        .and_then(|name| name.to_str())
        .map(str::to_owned)
        .ok_or_else(|| PackageError::InvalidManifest {
            path: path.to_path_buf(),
            message: "path must have a valid UTF-8 name".into(),
        })
}

fn cargo_identifier(input: &str) -> String {
    let identifier: String = input
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    let identifier = identifier.trim_matches('_');
    if identifier.is_empty() {
        "package".into()
    } else {
        identifier.into()
    }
}

fn relative_path(from: &Path, to: &Path) -> PathBuf {
    let from = from.components().collect::<Vec<_>>();
    let to = to.components().collect::<Vec<_>>();
    let common = from
        .iter()
        .zip(&to)
        .take_while(|(left, right)| left == right)
        .count();
    let mut result = PathBuf::new();
    for _ in common..from.len() {
        result.push("..");
    }
    for component in &to[common..] {
        result.push(component.as_os_str());
    }
    result
}

fn toml_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn is_generated_profile(profile_dir: &Path) -> bool {
    fs::read_to_string(profile_dir.join("Cargo.toml"))
        .map(|contents| contents.starts_with(GENERATED_MARKER))
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn workspace() -> PathBuf {
        let root = std::env::temp_dir().join(format!(
            "magic-pkg-test-{}",
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&root).unwrap();
        root
    }

    #[test]
    fn sync_creates_profiles_and_removes_disabled_ones() {
        let root = workspace();
        let package = root.join("packages/acme/inspector");
        fs::create_dir_all(package.join("editor")).unwrap();
        fs::write(
            package.join("editor/Cargo.toml"),
            "[package]\nname = \"acme-inspector\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
        )
        .unwrap();
        fs::write(
            package.join("package.json"),
            r#"{"name":"inspector","version":"1.2.3","targets":["editor"]}"#,
        )
        .unwrap();
        let manager = PackageManager::new(&root);
        assert_eq!(manager.sync_profiles().unwrap().written_profiles, 1);
        assert!(
            root.join("profiles/editor/acme_inspector/Cargo.toml")
                .is_file()
        );
        fs::write(
            package.join("package.json"),
            r#"{"name":"inspector","version":"1.2.3","status":"disabled","targets":[]}"#,
        )
        .unwrap();
        assert_eq!(manager.sync_profiles().unwrap().removed_profiles, 1);
        assert!(!root.join("profiles/editor/acme_inspector").exists());
        fs::remove_dir_all(root).unwrap();
    }
}
