//! Package discovery and Cargo dependency management for MagicBevy.

use magic_core::mgwarn;
use serde::Deserialize;
use std::collections::BTreeSet;
use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

const AUTO_HEADER: &str = "# Auto-generated by magic_pkg. Do not edit manually.";
const AUTO_RS_HEADER: &str = "// Auto-generated by magic_pkg. Do not edit manually.";

#[derive(Debug)]
pub enum PackageError {
    Io {
        path: PathBuf,
        source: io::Error,
    },
    Manifest {
        path: PathBuf,
        source: serde_json::Error,
    },
    InvalidManifest {
        path: PathBuf,
        message: String,
    },
    DuplicateId(String),
    AlreadyExists(PathBuf),
    InvalidArgument(String),
}

impl fmt::Display for PackageError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => write!(f, "I/O error at {}: {source}", path.display()),
            Self::Manifest { path, source } => write!(
                f,
                "Invalid package manifest at {}: {source}",
                path.display()
            ),
            Self::InvalidManifest { path, message } => write!(
                f,
                "Invalid package manifest at {}: {message}",
                path.display()
            ),
            Self::DuplicateId(id) => write!(f, "Duplicate package identifier: {id}"),
            Self::AlreadyExists(path) => write!(f, "Package already exists at {}", path.display()),
            Self::InvalidArgument(message) => write!(f, "Invalid argument: {message}"),
        }
    }
}

impl std::error::Error for PackageError {}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum PackageTarget {
    Editor,
    Runtime,
}

impl PackageTarget {
    fn directory(self) -> &'static str {
        match self {
            Self::Editor => "editor",
            Self::Runtime => "runtime",
        }
    }

    fn manifest_value(self) -> &'static str {
        match self {
            Self::Editor => "editor",
            Self::Runtime => "runtime",
        }
    }
}

#[derive(Debug, Deserialize)]
struct RawManifest {
    name: String,
    version: String,
    #[serde(default)]
    enabled: Option<bool>,
    #[serde(default)]
    status: Option<String>,
    #[serde(default)]
    targets: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PackageManifest {
    pub vendor: String,
    pub name: String,
    pub version: String,
    pub enabled: bool,
    pub targets: BTreeSet<PackageTarget>,
    pub root: PathBuf,
}

impl PackageManifest {
    pub fn id(&self) -> String {
        format!("{}/{}", self.vendor, self.name)
    }

    fn dependency_identifier(&self) -> String {
        format!(
            "{}_{}",
            cargo_identifier(&self.vendor),
            cargo_identifier(&self.name)
        )
    }
}

#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct SyncReport {
    pub discovered: usize,
    pub enabled: usize,
    pub editor_packages: usize,
    pub runtime_packages: usize,
    pub updated_manifests: usize,
    pub updated_code_files: usize,
}

pub struct PackageManager {
    packages_root: PathBuf,
    editor_manifest: PathBuf,
    runtime_manifest: PathBuf,
    editor_lib_rs: PathBuf,
    runtime_lib_rs: PathBuf,
}

impl PackageManager {
    pub fn new(start_path: impl Into<PathBuf>) -> Self {
        let workspace_root = find_workspace_root(&start_path.into());
        
        let editor_manifest = find_crate_manifest(&workspace_root, "magic_pkg_editor")
            .unwrap_or_else(|| workspace_root.join("magic_editor/magic_pkg_editor/Cargo.toml"));
        let runtime_manifest = find_crate_manifest(&workspace_root, "magic_pkg_runtime")
            .unwrap_or_else(|| workspace_root.join("magic_runtime/magic_pkg_runtime/Cargo.toml"));

        let editor_lib_rs = editor_manifest
            .parent()
            .map(|p| p.join("src/lib.rs"))
            .unwrap_or_else(|| workspace_root.join("magic_editor/magic_pkg_editor/src/lib.rs"));

        let runtime_lib_rs = runtime_manifest
            .parent()
            .map(|p| p.join("src/lib.rs"))
            .unwrap_or_else(|| workspace_root.join("magic_runtime/magic_pkg_runtime/src/lib.rs"));

        Self {
            packages_root: workspace_root.join("packages"),
            editor_manifest,
            runtime_manifest,
            editor_lib_rs,
            runtime_lib_rs,
        }
    }

    pub fn discover(&self) -> Result<Vec<PackageManifest>, PackageError> {
        if !self.packages_root.exists() {
            return Ok(Vec::new());
        }

        let mut packages = Vec::new();
        let mut identifiers = BTreeSet::new();
        for vendor_entry in read_directories(&self.packages_root)? {
            let vendor = file_name(&vendor_entry)?;
            for package_root in read_directories(&vendor_entry)? {
                let package = self.read_manifest(&vendor, package_root)?;
                if !identifiers.insert(package.dependency_identifier()) {
                    return Err(PackageError::DuplicateId(package.id()));
                }
                packages.push(package);
            }
        }
        packages.sort_by(|left, right| left.id().cmp(&right.id()));
        Ok(packages)
    }

    pub fn sync(&self) -> Result<SyncReport, PackageError> {
        let packages = self.discover()?;
        let mut report = SyncReport {
            discovered: packages.len(),
            ..SyncReport::default()
        };

        let mut editor_deps = Vec::new();
        let mut runtime_deps = Vec::new();

        let mut editor_aliases = Vec::new();
        let mut runtime_aliases = Vec::new();

        for package in packages.into_iter().filter(|package| package.enabled) {
            report.enabled += 1;
            let alias = format!("package_{}", package.dependency_identifier());

            for target in &package.targets {
                let crate_path = package.root.join(target.directory());
                let crate_manifest = crate_path.join("Cargo.toml");
                let crate_name = package_name(&crate_manifest)?;

                match target {
                    PackageTarget::Editor => {
                        report.editor_packages += 1;
                        editor_deps.push((alias.clone(), crate_name, crate_path));
                        editor_aliases.push(alias.clone());
                    }
                    PackageTarget::Runtime => {
                        report.runtime_packages += 1;
                        runtime_deps.push((alias.clone(), crate_name, crate_path));
                        runtime_aliases.push(alias.clone());
                    }
                }
            }
        }

        if self.editor_manifest.exists() {
            if update_manifest_dependencies(&self.editor_manifest, &editor_deps)? {
                report.updated_manifests += 1;
            }
        } else {
            mgwarn!(
                "magic_pkg",
                "Editor manifest not found at {}",
                self.editor_manifest.display()
            );
        }

        if self.runtime_manifest.exists() {
            if update_manifest_dependencies(&self.runtime_manifest, &runtime_deps)? {
                report.updated_manifests += 1;
            }
        } else {
            mgwarn!(
                "magic_pkg",
                "Runtime manifest not found at {}",
                self.runtime_manifest.display()
            );
        }

        if update_editor_lib_register(&self.editor_lib_rs, &editor_aliases)? {
            report.updated_code_files += 1;
        }

        if update_runtime_lib_register(&self.runtime_lib_rs, &runtime_aliases)? {
            report.updated_code_files += 1;
        }

        Ok(report)
    }

    pub fn init_package(
        &self,
        vendor: &str,
        name: &str,
        targets: impl IntoIterator<Item = PackageTarget>,
    ) -> Result<(PackageManifest, SyncReport), PackageError> {
        validate_segment("vendor", vendor)?;
        validate_segment("package name", name)?;
        let targets = targets.into_iter().collect::<BTreeSet<_>>();
        if targets.is_empty() {
            return Err(PackageError::InvalidArgument(
                "at least one target is required".into(),
            ));
        }

        let root = self.packages_root.join(vendor).join(name);
        if root.exists() {
            return Err(PackageError::AlreadyExists(root));
        }

        fs::create_dir_all(root.join("assets")).map_err(|source| PackageError::Io {
            path: root.clone(),
            source,
        })?;
        fs::write(root.join("assets/.gitkeep"), "").map_err(|source| PackageError::Io {
            path: root.join("assets/.gitkeep"),
            source,
        })?;

        let target_values = targets
            .iter()
            .map(|target| format!("\"{}\"", target.manifest_value()))
            .collect::<Vec<_>>()
            .join(", ");
        let manifest = format!(
            "{{\n  \"name\": \"{name}\",\n  \"version\": \"0.1.0\",\n  \"status\": \"enabled\",\n  \"targets\": [{target_values}]\n}}\n"
        );
        fs::write(root.join("package.json"), manifest).map_err(|source| PackageError::Io {
            path: root.join("package.json"),
            source,
        })?;

        for target in &targets {
            self.write_target_template(&root, vendor, name, *target)?;
        }

        let manifest_data = self.read_manifest(vendor, root)?;
        let report = self.sync()?;
        Ok((manifest_data, report))
    }

    pub fn remove_package(&self, vendor: &str, name: &str) -> Result<(String, SyncReport), PackageError> {
        validate_segment("vendor", vendor)?;
        validate_segment("package name", name)?;

        let root = self.packages_root.join(vendor).join(name);
        if !root.exists() {
            return Err(PackageError::InvalidArgument(format!(
                "Package '{vendor}/{name}' does not exist at {}",
                root.display()
            )));
        }

        fs::remove_dir_all(&root).map_err(|source| PackageError::Io {
            path: root.clone(),
            source,
        })?;

        let vendor_dir = self.packages_root.join(vendor);
        if vendor_dir.exists() {
            if let Ok(mut entries) = fs::read_dir(&vendor_dir) {
                if entries.next().is_none() {
                    let _ = fs::remove_dir(&vendor_dir);
                }
            }
        }

        let report = self.sync()?;

        Ok((format!("{vendor}/{name}"), report))
    }

    pub fn set_package_status(
        &self,
        vendor: &str,
        name: &str,
        enabled: bool,
    ) -> Result<(String, SyncReport), PackageError> {
        validate_segment("vendor", vendor)?;
        validate_segment("package name", name)?;

        let root = self.packages_root.join(vendor).join(name);
        let manifest_path = root.join("package.json");

        if !manifest_path.is_file() {
            return Err(PackageError::InvalidArgument(format!(
                "Package '{vendor}/{name}' does not exist at {}",
                root.display()
            )));
        }

        let content = fs::read_to_string(&manifest_path).map_err(|source| PackageError::Io {
            path: manifest_path.clone(),
            source,
        })?;

        let mut json_val: serde_json::Value =
            serde_json::from_str(&content).map_err(|source| PackageError::Manifest {
                path: manifest_path.clone(),
                source,
            })?;

        if let Some(obj) = json_val.as_object_mut() {
            let status_str = if enabled { "enabled" } else { "disabled" };
            obj.insert(
                "status".to_string(),
                serde_json::Value::String(status_str.to_string()),
            );
            obj.remove("enabled");
        }

        let updated_json = serde_json::to_string_pretty(&json_val).map_err(|source| {
            PackageError::InvalidManifest {
                path: manifest_path.clone(),
                message: format!("Failed to serialize JSON: {source}"),
            }
        })?;

        fs::write(&manifest_path, updated_json).map_err(|source| PackageError::Io {
            path: manifest_path,
            source,
        })?;

        let report = self.sync()?;

        Ok((format!("{vendor}/{name}"), report))
    }

    fn write_target_template(
        &self,
        package_root: &Path,
        vendor: &str,
        name: &str,
        target: PackageTarget,
    ) -> Result<(), PackageError> {
        let target_root = package_root.join(target.directory());
        let source_root = target_root.join("src");
        fs::create_dir_all(&source_root).map_err(|source| PackageError::Io {
            path: source_root.clone(),
            source,
        })?;
        let crate_name = format!(
            "magic_package_{}_{}_{}",
            cargo_identifier(vendor),
            cargo_identifier(name),
            target.manifest_value()
        );
        let cargo_toml = format!(
            "{AUTO_HEADER}\n[package]\nname = \"{crate_name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n"
        );
        fs::write(target_root.join("Cargo.toml"), cargo_toml).map_err(|source| {
            PackageError::Io {
                path: target_root.join("Cargo.toml"),
                source,
            }
        })?;
        let source = "pub fn register<T>(_manager: &mut T) {}\n";
        fs::write(source_root.join("lib.rs"), source).map_err(|source| PackageError::Io {
            path: source_root.join("lib.rs"),
            source,
        })
    }

    fn read_manifest(&self, vendor: &str, root: PathBuf) -> Result<PackageManifest, PackageError> {
        let path = root.join("package.json");
        if !path.is_file() {
            return Err(PackageError::InvalidManifest {
                path,
                message: "package.json is required".into(),
            });
        }
        let content = fs::read_to_string(&path).map_err(|source| PackageError::Io {
            path: path.clone(),
            source,
        })?;
        let raw: RawManifest =
            serde_json::from_str(&content).map_err(|source| PackageError::Manifest {
                path: path.clone(),
                source,
            })?;
        if raw.name.trim().is_empty() || raw.version.trim().is_empty() {
            return Err(PackageError::InvalidManifest {
                path,
                message: "name and version must not be empty".into(),
            });
        }
        let enabled = match raw.status.as_deref() {
            None => raw.enabled.unwrap_or(true),
            Some("enabled") if raw.enabled != Some(false) => true,
            Some("disabled") if raw.enabled != Some(true) => false,
            Some("enabled") | Some("disabled") => {
                return Err(PackageError::InvalidManifest {
                    path,
                    message: "status and enabled disagree".into(),
                });
            }
            Some(status) => {
                return Err(PackageError::InvalidManifest {
                    path,
                    message: format!("unsupported status '{status}'"),
                });
            }
        };
        let mut targets = BTreeSet::new();
        for target in raw.targets {
            match target.as_str() {
                "editor" => {
                    targets.insert(PackageTarget::Editor);
                }
                "runtime" => {
                    targets.insert(PackageTarget::Runtime);
                }
                _ => {
                    return Err(PackageError::InvalidManifest {
                        path,
                        message: format!("unsupported target '{target}'"),
                    });
                }
            }
        }
        if enabled && targets.is_empty() {
            return Err(PackageError::InvalidManifest {
                path,
                message: "enabled packages require at least one target".into(),
            });
        }
        for target in &targets {
            let crate_manifest = root.join(target.directory()).join("Cargo.toml");
            if !crate_manifest.is_file() {
                return Err(PackageError::InvalidManifest {
                    path: crate_manifest,
                    message: format!("{} target requires a Cargo crate", target.directory()),
                });
            }
        }
        Ok(PackageManifest {
            vendor: vendor.to_owned(),
            name: raw.name,
            version: raw.version,
            enabled,
            targets,
            root,
        })
    }
}

fn update_editor_lib_register(lib_path: &Path, aliases: &[String]) -> Result<bool, PackageError> {
    if let Some(parent) = lib_path.parent() {
        let _ = fs::create_dir_all(parent);
    }

    let mut body = String::new();
    body.push_str(&format!("{AUTO_RS_HEADER}\n\n"));
    body.push_str("pub fn register_all_packages<T>(_manager: &mut T) {\n");

    for alias in aliases {
        body.push_str(&format!("    {alias}::register(_manager);\n"));
    }

    body.push_str("}\n");

    let current = fs::read_to_string(lib_path).unwrap_or_default();
    if current == body {
        Ok(false)
    } else {
        fs::write(lib_path, body).map_err(|source| PackageError::Io {
            path: lib_path.to_path_buf(),
            source,
        })?;
        Ok(true)
    }
}

fn update_runtime_lib_register(lib_path: &Path, aliases: &[String]) -> Result<bool, PackageError> {
    if let Some(parent) = lib_path.parent() {
        let _ = fs::create_dir_all(parent);
    }

    let mut body = String::new();
    body.push_str(&format!("{AUTO_RS_HEADER}\n\n"));
    body.push_str("pub fn register_all_packages<T>(_manager: &mut T) {\n");

    for alias in aliases {
        body.push_str(&format!("    {alias}::register(_manager);\n"));
    }

    body.push_str("}\n");

    let current = fs::read_to_string(lib_path).unwrap_or_default();
    if current == body {
        Ok(false)
    } else {
        fs::write(lib_path, body).map_err(|source| PackageError::Io {
            path: lib_path.to_path_buf(),
            source,
        })?;
        Ok(true)
    }
}

fn find_workspace_root(start_dir: &Path) -> PathBuf {
    let mut current = start_dir.to_path_buf();
    loop {
        let manifest = current.join("Cargo.toml");
        if manifest.is_file() {
            if let Ok(content) = fs::read_to_string(&manifest) {
                if content.contains("[workspace]") {
                    return current;
                }
            }
        }
        if !current.pop() {
            break;
        }
    }
    start_dir.to_path_buf()
}

fn find_crate_manifest(workspace_root: &Path, crate_name: &str) -> Option<PathBuf> {
    let short_name = crate_name.trim_start_matches("magic_pkg_");

    let candidates = [
        workspace_root
            .join(format!("magic_{short_name}"))
            .join(crate_name)
            .join("Cargo.toml"),
        workspace_root
            .join(format!("magic_{short_name}"))
            .join("Cargo.toml"),
        workspace_root.join(crate_name).join("Cargo.toml"),
        workspace_root.join(short_name).join("Cargo.toml"),
        workspace_root
            .join("crates")
            .join(crate_name)
            .join("Cargo.toml"),
        workspace_root
            .join("crates")
            .join(short_name)
            .join("Cargo.toml"),
    ];

    for candidate in &candidates {
        if candidate.is_file() {
            if let Ok(name) = package_name(candidate) {
                if name == crate_name {
                    return Some(candidate.clone());
                }
            }
        }
    }

    fn walk(dir: &Path, crate_name: &str, depth: usize) -> Option<PathBuf> {
        if depth > 3 {
            return None;
        }
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.filter_map(Result::ok) {
                let path = entry.path();
                if path.is_dir() {
                    let folder_name = path.file_name().unwrap_or_default().to_string_lossy();
                    if folder_name.starts_with('.')
                        || folder_name == "target"
                        || folder_name == "packages"
                    {
                        continue;
                    }
                    let manifest = path.join("Cargo.toml");
                    if manifest.is_file() {
                        if let Ok(name) = package_name(&manifest) {
                            if name == crate_name {
                                return Some(manifest);
                            }
                        }
                    }
                    if let Some(found) = walk(&path, crate_name, depth + 1) {
                        return Some(found);
                    }
                }
            }
        }
        None
    }

    walk(workspace_root, crate_name, 1)
}

fn update_manifest_dependencies(
    manifest_path: &Path,
    dependencies: &[(String, String, PathBuf)],
) -> Result<bool, PackageError> {
    let content = fs::read_to_string(manifest_path).map_err(|source| PackageError::Io {
        path: manifest_path.to_path_buf(),
        source,
    })?;

    let manifest_dir = manifest_path.parent().unwrap_or_else(|| Path::new("."));

    let lines: Vec<&str> = content
        .lines()
        .filter(|line| line.trim() != AUTO_HEADER)
        .collect();

    let mut new_lines: Vec<String> = Vec::new();
    let mut in_dependencies = false;
    let mut dependencies_found = false;

    for line in lines {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            if trimmed == "[dependencies]" {
                in_dependencies = true;
                dependencies_found = true;
                new_lines.push(line.to_string());
                for (alias, crate_name, crate_path) in dependencies {
                    let rel_path = relative_path(manifest_dir, crate_path);
                    let path_str = toml_path(&rel_path);
                    new_lines.push(format!(
                        "{alias} = {{ package = \"{crate_name}\", path = \"{path_str}\" }}"
                    ));
                }
                continue;
            } else {
                in_dependencies = false;
            }
        }

        if in_dependencies {
            if trimmed.starts_with("package_")
                || trimmed == "# BEGIN MAGIC_PKG DEPENDENCIES"
                || trimmed == "# END MAGIC_PKG DEPENDENCIES"
            {
                continue;
            }
        } else if trimmed == "# BEGIN MAGIC_PKG DEPENDENCIES"
            || trimmed == "# END MAGIC_PKG DEPENDENCIES"
        {
            continue;
        }

        new_lines.push(line.to_string());
    }

    if !dependencies_found {
        if !new_lines.is_empty() && !new_lines.last().unwrap().is_empty() {
            new_lines.push(String::new());
        }
        new_lines.push("[dependencies]".to_string());
        for (alias, crate_name, crate_path) in dependencies {
            let rel_path = relative_path(manifest_dir, crate_path);
            let path_str = toml_path(&rel_path);
            new_lines.push(format!(
                "{alias} = {{ package = \"{crate_name}\", path = \"{path_str}\" }}"
            ));
        }
    }

    let updated_content = format!("{AUTO_HEADER}\n{}\n", new_lines.join("\n"));

    if updated_content == content {
        Ok(false)
    } else {
        fs::write(manifest_path, updated_content).map_err(|source| PackageError::Io {
            path: manifest_path.to_path_buf(),
            source,
        })?;
        Ok(true)
    }
}

fn validate_segment(kind: &str, value: &str) -> Result<(), PackageError> {
    if value.is_empty()
        || !value.chars().all(|character| {
            character.is_ascii_alphanumeric() || character == '_' || character == '-'
        })
    {
        return Err(PackageError::InvalidArgument(format!(
            "{kind} must use only ASCII letters, digits, '_' or '-'"
        )));
    }
    Ok(())
}

fn package_name(manifest_path: &Path) -> Result<String, PackageError> {
    let contents = fs::read_to_string(manifest_path).map_err(|source| PackageError::Io {
        path: manifest_path.to_path_buf(),
        source,
    })?;
    let mut in_package_table = false;
    for raw_line in contents.lines() {
        let line = raw_line.trim();
        if line.starts_with('[') {
            in_package_table = line == "[package]";
            continue;
        }
        if !in_package_table {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        if key.trim() != "name" {
            continue;
        }
        let value = value.trim();
        let name = match value.chars().next() {
            Some('"') => value[1..].split('"').next(),
            Some('\'') => value[1..].split('\'').next(),
            _ => None,
        };
        if let Some(name) = name.filter(|name| !name.trim().is_empty()) {
            return Ok(name.to_owned());
        }
    }
    Err(PackageError::InvalidManifest {
        path: manifest_path.to_path_buf(),
        message: "Cargo.toml requires a non-empty package.name".into(),
    })
}

fn read_directories(path: &Path) -> Result<Vec<PathBuf>, PackageError> {
    let entries = fs::read_dir(path).map_err(|source| PackageError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    Ok(entries
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .collect())
}

fn file_name(path: &Path) -> Result<String, PackageError> {
    path.file_name()
        .and_then(|name| name.to_str())
        .map(str::to_owned)
        .ok_or_else(|| PackageError::InvalidManifest {
            path: path.to_path_buf(),
            message: "path must have a valid UTF-8 name".into(),
        })
}

fn cargo_identifier(input: &str) -> String {
    let identifier: String = input
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    let identifier = identifier.trim_matches('_');
    if identifier.is_empty() {
        "package".into()
    } else {
        identifier.into()
    }
}

fn relative_path(from: &Path, to: &Path) -> PathBuf {
    let from = from.components().collect::<Vec<_>>();
    let to = to.components().collect::<Vec<_>>();
    let common = from
        .iter()
        .zip(&to)
        .take_while(|(left, right)| left == right)
        .count();
    let mut result = PathBuf::new();
    for _ in common..from.len() {
        result.push("..");
    }
    for component in &to[common..] {
        result.push(component.as_os_str());
    }
    result
}

fn toml_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}